export const endPoints = {
    root: '/',
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    createInfo: '/create/info',
    createProfileDoctor: '/create/profile-doctor',
    createInfoPatient: '/create/info-patient',
    homeIntro: '/home-intro',
    doctorManager: '/doctor-manager',
    doctorManagerJoinIdRoom: '/doctor-manager/room',
    meetingRoom: '/meeting-room',
    maps: '/maps',
    chatMessage: '/chat',
    registerScheduleAppointment: '/register-schedule-appointment',
    blog: '/blog',
};
