export {
    MenuGeneralExaminationIcon,
    MenuPeriodicHealthExaminationIcon,
    SlideShowHeartIcon,
    SlideShowBannerClinicIcon,
    ExploreClinicInformationLocationIcon,
    ExploreClinicInformationClockIcon,
    HealthInformationEndocrinologyIcon,
    HealthInformationCardiologyIcon,
    HealthInformationSexualHealthIcon,
    RemoteHealthConsultationVideoIcon,
    RemoteHealthConsultationChatIcon,
    FeelUnwellStethoscopeIcon,
    FeelUnwellLabIcon,
    PharmacyOnlineDeliveryIcon,
    PharmacyOnlineDiscountIcon,
} from './Icons';
